import { RawEvent, SOURCES, CATEGORIES } from '@/types/event';

export class TestScraper {
  async scrapeEvents(): Promise<RawEvent[]> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500));
    
    const sampleEvents: RawEvent[] = [
      // Existing local events (15km radius)
      {
        source: SOURCES.MUNICIPAL,
        sourceEventId: 'schlieren-1',
        title: 'Schlieremer Herbstmarkt',
        description: 'Traditioneller Herbstmarkt mit regionalen Produkten, Kürbissen und warmen Getränken.',
        lang: 'de',
        category: CATEGORIES.MARKET,
        startTime: new Date('2025-09-14T09:00:00'),
        endTime: new Date('2025-09-14T16:00:00'),
        venueName: 'Zentrum Schlieren',
        street: 'Bahnhofstrasse 1',
        postalCode: '8952',
        city: 'Schlieren',
        country: 'CH',
        lat: 47.3967,
        lon: 8.4472,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.schlieren.ch/events'
      },
      {
        source: SOURCES.MUNICIPAL,
        sourceEventId: 'dietikon-1', 
        title: 'Dietiker Stadtfest 2025',
        description: 'Großes Stadtfest mit Live-Musik, Food Trucks und Aktivitäten für die ganze Familie.',
        lang: 'de',
        category: CATEGORIES.FESTIVAL,
        startTime: new Date('2025-09-28T11:00:00'),
        endTime: new Date('2025-09-28T23:00:00'),
        venueName: 'Stadtpark Dietikon',
        street: 'Parkstrasse',
        postalCode: '8953',
        city: 'Dietikon',
        country: 'CH',
        lat: 47.4017,
        lon: 8.4008,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.dietikon.ch/stadtfest'
      },
      {
        source: SOURCES.ST,
        sourceEventId: 'test-1',
        title: 'Schlieremer Weihnachtsmarkt',
        description: 'Traditioneller Weihnachtsmarkt mit lokalen Produkten und warmen Getränken im Zentrum von Schlieren.',
        lang: 'de',
        category: CATEGORIES.SEASONAL,
        startTime: new Date('2025-12-15T10:00:00'),
        endTime: new Date('2025-12-15T20:00:00'),
        venueName: 'Stadtplatz Schlieren',
        street: 'Stadtplatz 1',
        postalCode: '8952',
        city: 'Schlieren',
        country: 'CH',
        lat: 47.396,
        lon: 8.447,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.schlieren.ch/weihnachtsmarkt',
        imageUrl: undefined
      },
      {
        source: SOURCES.LIMMATTAL,
        sourceEventId: 'test-2',
        title: 'Familienkonzert: Schweizer Volksmusik',
        description: 'Ein unterhaltsames Konzert für die ganze Familie mit traditioneller Schweizer Volksmusik.',
        lang: 'de',
        category: CATEGORIES.MUSIC,
        startTime: new Date('2025-09-20T14:00:00'),
        endTime: new Date('2025-09-20T16:00:00'),
        venueName: 'Gemeindesaal Dietikon',
        street: 'Bremgartnerstrasse 22',
        postalCode: '8953',
        city: 'Dietikon',
        country: 'CH',
        lat: 47.4017,
        lon: 8.4008,
        priceMin: 15,
        priceMax: 25,
        currency: 'CHF',
        url: 'https://www.dietikon.ch/events',
        imageUrl: undefined
      },
      {
        source: SOURCES.ST,
        sourceEventId: 'test-3',
        title: 'Zürich Herbstfest 2025',
        description: 'Großes Herbstfest mit regionalen Spezialitäten, Handwerk und Live-Musik im Herzen von Zürich.',
        lang: 'de',
        category: CATEGORIES.FESTIVAL,
        startTime: new Date('2025-10-10T11:00:00'),
        endTime: new Date('2025-10-12T22:00:00'),
        venueName: 'Münsterplatz Zürich',
        street: 'Münsterplatz',
        postalCode: '8001',
        city: 'Zürich',
        country: 'CH',
        lat: 47.3769,
        lon: 8.5417,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.zuerich.com/herbstfest',
        imageUrl: undefined
      },
      {
        source: SOURCES.LIMMATTAL,
        sourceEventId: 'test-4',
        title: 'Kindertheater: Der gestiefelte Kater',
        description: 'Ein märchenhaftes Theaterstück für Kinder ab 4 Jahren mit professionellen Schauspielern.',
        lang: 'de',
        category: CATEGORIES.FAMILY,
        startTime: new Date('2025-09-25T15:00:00'),
        endTime: new Date('2025-09-25T16:30:00'),
        venueName: 'Kulturzentrum Urdorf',
        street: 'Bahnhofstrasse 5',
        postalCode: '8902',
        city: 'Urdorf',
        country: 'CH',
        lat: 47.3889,
        lon: 8.4244,
        priceMin: 8,
        priceMax: 12,
        currency: 'CHF',
        url: 'https://www.urdorf.ch/kultur',
        imageUrl: undefined
      },
      {
        source: SOURCES.ST,
        sourceEventId: 'test-5',
        title: 'Sportfest Oberengstringen',
        description: 'Jährliches Sportfest mit verschiedenen Aktivitäten für alle Altersgruppen.',
        lang: 'de',
        category: CATEGORIES.SPORTS,
        startTime: new Date('2025-09-15T09:00:00'),
        endTime: new Date('2025-09-15T17:00:00'),
        venueName: 'Sportplatz Oberengstringen',
        street: 'Sportweg 10',
        postalCode: '8102',
        city: 'Oberengstringen',
        country: 'CH',
        lat: 47.4122,
        lon: 8.4503,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: undefined,
        imageUrl: undefined
      },
      // Regional events (50km radius)
      {
        source: SOURCES.ST,
        sourceEventId: 'basel-1',
        title: 'Basel Herbstmesse 2025',
        description: 'Die größte Herbstmesse der Schweiz mit Fahrgeschäften, Ständen und regionalen Spezialitäten.',
        lang: 'de',
        category: CATEGORIES.FESTIVAL,
        startTime: new Date('2025-10-25T10:00:00'),
        endTime: new Date('2025-11-10T22:00:00'),
        venueName: 'Münsterplatz Basel',
        street: 'Münsterplatz',
        postalCode: '4051',
        city: 'Basel',
        country: 'CH',
        lat: 47.5584,
        lon: 7.5887,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.basel.com/herbstmesse'
      },
      {
        source: SOURCES.ST,
        sourceEventId: 'luzern-1',
        title: 'Luzerner Fasnacht Vorprogramm',
        description: 'Traditionelle Fasnachtsveranstaltungen und Guggenmusik-Auftritte im Herbst.',
        lang: 'de',
        category: CATEGORIES.CULTURE,
        startTime: new Date('2025-09-21T19:00:00'),
        endTime: new Date('2025-09-21T23:00:00'),
        venueName: 'Altstadt Luzern',
        street: 'Weinmarkt',
        postalCode: '6004',
        city: 'Luzern',
        country: 'CH',
        lat: 47.0505,
        lon: 8.3064,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.luzern.com/fasnacht'
      },
      // Special events (100km+ radius) - Alpsabzug & major festivals
      {
        source: SOURCES.ST,
        sourceEventId: 'alpabzug-1',
        title: 'Alpabzug Appenzell - Viehscheid',
        description: 'Traditioneller Alpabzug mit geschmückten Kühen, Sennen und Alphornbläsern im Appenzell.',
        lang: 'de',
        category: CATEGORIES.ALPSABZUG,
        startTime: new Date('2025-09-27T08:00:00'),
        endTime: new Date('2025-09-27T17:00:00'),
        venueName: 'Dorfzentrum Appenzell',
        street: 'Hauptgasse',
        postalCode: '9050',
        city: 'Appenzell',
        country: 'CH',
        lat: 47.3302,
        lon: 9.4095,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.appenzell.ch/alpabzug'
      },
      {
        source: SOURCES.ST,
        sourceEventId: 'bern-1',
        title: 'Berner Zibelemärit 2025',
        description: 'Der traditionelle Zwiebelmarkt in der Berner Altstadt mit Handwerk und regionalen Produkten.',
        lang: 'de',
        category: CATEGORIES.MARKET,
        startTime: new Date('2025-11-24T05:00:00'),
        endTime: new Date('2025-11-24T16:00:00'),
        venueName: 'Altstadt Bern',
        street: 'Bundesplatz',
        postalCode: '3011',
        city: 'Bern',
        country: 'CH',
        lat: 46.9481,
        lon: 7.4474,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.bern.com/zibelemarit'
      },
      // More local Limmattal events
      {
        source: SOURCES.MUNICIPAL,
        sourceEventId: 'urdorf-2',
        title: 'Urdorfer Herbstkonzert',
        description: 'Klassisches Konzert der Musikschule Urdorf mit jungen Talenten aus der Region.',
        lang: 'de',
        category: CATEGORIES.MUSIC,
        startTime: new Date('2025-09-19T20:00:00'),
        endTime: new Date('2025-09-19T22:00:00'),
        venueName: 'Reformierte Kirche Urdorf',
        street: 'Kirchgasse 10',
        postalCode: '8902',
        city: 'Urdorf',
        country: 'CH',
        lat: 47.3889,
        lon: 8.4244,
        priceMin: 10,
        priceMax: 20,
        currency: 'CHF',
        url: 'https://www.urdorf.ch/musik'
      },
      {
        source: SOURCES.MUNICIPAL,
        sourceEventId: 'oberengstringen-2',
        title: 'Gemeindeversammlung Oberengstringen',
        description: 'Öffentliche Gemeindeversammlung mit Diskussion über lokale Projekte und Abstimmungen.',
        lang: 'de',
        category: CATEGORIES.COMMUNITY,
        startTime: new Date('2025-09-30T19:30:00'),
        endTime: new Date('2025-09-30T21:30:00'),
        venueName: 'Gemeindehouse Oberengstringen',
        street: 'Zürcherstrasse 1',
        postalCode: '8102',
        city: 'Oberengstringen',
        country: 'CH',
        lat: 47.4122,
        lon: 8.4503,
        priceMin: 0,
        priceMax: undefined,
        currency: 'CHF',
        url: 'https://www.oberengstringen.ch/gemeindeversammlung'
      }
    ];

    console.log(`Test scraper: Generated ${sampleEvents.length} sample events`);
    return sampleEvents;
  }
}